In [1]:
import numpy as np

### all & any

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [4]:
a < 1

array([ True, False, False, False, False, False, False, False, False,
       False])

In [5]:
np.all(a < 5)

False

In [6]:
np.any(a < 5)

True

In [8]:
np.all(a < 20)

True

### comparison operation

In [9]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b

array([False,  True, False])

In [10]:
test_a == test_b

array([False, False, False])

In [11]:
(test_a > test_b).any()

True

In [15]:
(test_a > test_b).all()

False

### comparison operation #2

In [12]:
a = np.array([1, 3, 0], float)
np.logical_and(0 < a, a < 3)

array([ True, False, False])

In [13]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [14]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])

### np.where

In [17]:
a

array([1., 3., 0.])

In [21]:
np.where(a > 2) # index 값

(array([1]),)

In [19]:
np.where(a > 1)

(array([1]),)

In [20]:
np.where(a < 3)[0]

array([0, 2])

In [23]:
np.where(a < 3, 3, 2)    # where(condition, TRUE, FALSE)

array([3, 2, 3])

In [25]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
np.where(a > 10)

(array([6, 7, 8, 9]),)

In [27]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [28]:
np.isfinite(a)

array([ True, False, False])

### argmax & argmin
* array내 최대값 또는 최소값의 index를 반환

In [32]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
np.argmax(a), np.argmin(a)

(5, 0)

In [34]:
a.argsort() # 크기 순서대로 idex 출력

array([0, 1, 7, 2, 3, 4, 6, 5])

In [35]:
# axis 기반의 반환
a = np.array([[1, 2, 4, 7],[9, 88, 6, 45],[9, 76, 3, 4]])
np.argmax(a, axis=1), np.argmin(a, axis=0)

(array([3, 1, 1]), array([0, 0, 2, 2]))

### boolean & fancy index

In [36]:
# 특정 조건에 따른 값을 배열 형태로 추출
# Comparison operation 함수들도 모두 사용 가능

In [37]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [38]:
# 조건이 True인 index의 element만 추출
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [39]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

In [40]:
# fancy index
# numpy는 array를 index value로 사용해서 값 추출

In [42]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int) # 반드시 integer로 선언
a[b] # bracket index, b 배열의 값을 index로 하여 a의 값들을 추출

array([2., 2., 4., 8., 6., 4.])

In [43]:
a.take(b) # take 함수 : bracket index와 같은 효과

array([2., 2., 4., 8., 6., 4.])

In [45]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b, c]  # b를 row index, c를 column index로 변환하여 표사

array([ 1.,  4., 16., 16.,  4.])

In [46]:
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])

### load txt

In [ ]:
a = np.loadtxt("./파일명.txt", delimiter='\t')
a

In [ ]:
a_int = a.astype(int)
a_int_3 = a_int[:3]

In [ ]:
np.savetxt("int_data_2.csv", a_int_3, fmt="%.2e", delimiter=',')

### numpy object - npy

In [ ]:
np.save("파일명", arr=a_int)

In [ ]:
a_test = np.load(file="파일명.npy")
a_test

In [ ]:
npy_array = np.load(file="파일명.npy")
npy_array[:3]